services:

  postgres:
    restart: always
    container_name: "postgres"
    hostname: postgres
    networks:
      - app-network
    image: 'postgres:16.1-alpine'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"

  security:
    build:
      context: .
    container_name: "security"
    networks:
      - app-network
    depends_on:
      - postgres
    ports:
      - "8081:8081"

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
    driver: local