services:

  database:
    restart: always
    container_name: postgres_t1_4
    hostname: postgres_t1_4
    image: 'postgres:16.1-alpine'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"

  security:
    build:
      context: .
    container_name: "security"
    networks:
      - app-network
    depends_on:
      - database
    ports:
      - "8081:8081"

networks:
  app-network:
    driver: bridge