CREATE TABLE IF NOT EXISTS t_roles
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role    VARCHAR(20)                    NOT NULL,

    user_id BIGINT REFERENCES t_users (id) NOT NULL
);
